USE [OmmcMes]
GO

/****** Object:  Table [dbo].[MST_EQUIPALARM]    Script Date: 4/16/2018 1:03:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MST_PLC_TAGS](
	[PLC_IP] [varchar](15) NOT NULL,
	[TAG_ID] [varchar](50) NOT NULL,
	[WW_ITEM_NAME] [varchar](100) NULL,
	[DESCRIPTION] [varchar](50) NULL,
 CONSTRAINT [PK_MST_PLC_TAGS] PRIMARY KEY CLUSTERED 
(
	[PLC_IP] ASC,
	[TAG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO


